# Created with YamlCreate.ps1 v2.4.1 $debug=QUSU.CRLF.7-4-2.Win32NT
# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.10.0.schema.json

PackageIdentifier: HelmutBuhler.8GadgetPack
PackageVersion: 38.0.0
PackageLocale: zh-CN
Publisher: GadgetPack.net
PublisherUrl: https://gadgetpack.net/
PublisherSupportUrl: https://gadgetpack.net/Feedback.php
# PrivacyUrl:
Author: Helmut Buhler
PackageName: 8GadgetPack
PackageUrl: https://gadgetpack.net/
License: 免费软件
# LicenseUrl:
Copyright: © 2025 Helmut Buhler
# CopyrightUrl:
ShortDescription: GadgetPack（以前称为 8GadgetPack）使得在 Windows 11/10 上使用小工具成为可能。
# Description:
# Moniker:
Tags:
- 侧栏
- 小工具
- 挂件
# ReleaseNotes:
ReleaseNotesUrl: https://gadgetpack.net/changelog.html
# PurchaseUrl:
# InstallationNotes:
Documentations:
- DocumentLabel: 指南
  DocumentUrl: https://gadgetpack.net/howto.html
- DocumentLabel: 常见问题
  DocumentUrl: https://gadgetpack.net/faq.html
ManifestType: locale
ManifestVersion: 1.10.0
